language: julia

sudo: required

services:
  - docker

os:
  - linux

julia:
  - 0.4
  - 0.5
  - nightly

script:
  - travis_wait 30 julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ValidatedNumerics"); Pkg.test("ValidatedNumerics", coverage=true)'


matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
- julia -e 'cd(Pkg.dir("ValidatedNumerics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
