language: julia

sudo: required

services:
  - docker

os:
  - linux

julia:
  - 0.4
  - 0.5
  - nightly

script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build(\"${JL_PKG}\")'
  - if [ -f test/runtests.jl ]; then
      travis_wait 30 julia --check-bounds=yes -e 'Pkg.test(\"${JL_PKG}\", coverage=true)'
    fi

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
- julia -e 'cd(Pkg.dir("ValidatedNumerics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
